import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, persistedState, expectComfortable, expectImagesLoaded } from './helpers.js'

test('parent assistant stays off by default and all suggestions remain parent-controlled', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1024 })
  await setupFamily(page)
  await unlockParent(page, '/parent/assistant')
  await expect(page.getByRole('heading', { name: '小队助手' })).toBeVisible()
  const master = page.getByRole('checkbox', { name: /启用小队助手/ })
  await expect(master).not.toBeChecked()
  await expect(page.getByText('外部 AI 上传：关闭')).toBeVisible()
  await expect(page.getByRole('button', { name: '整理本周建议' })).toBeDisabled()
  await master.check()
  await page.getByRole('button', { name: '整理本周建议' }).click()
  await expect(page.locator('.assistant-suggestion')).toHaveCount(1)
  await expect(page.getByText('从一个五分钟小行动开始')).toBeVisible()
  await expect(page.getByText('家长确认前，不会生效')).toBeVisible()
  await expectComfortable(page); await expectImagesLoaded(page)
  await page.screenshot({ path: 'artifacts/visual-qa/120-assistant-parent-desktop.png', fullPage: true })
  await page.getByRole('navigation', { name: '家长导航' }).getByRole('link', { name: '成长', exact: true }).click()
  await expect(page.getByRole('heading', { name: '看见真实的小变化' })).toBeVisible()
  await expect(page.locator('.calm-metrics article')).toHaveCount(5)
  await expect(page.getByText('一起完成，不等于需要变少的陪伴')).toBeVisible()
  await expectComfortable(page); await expectImagesLoaded(page)
  await page.screenshot({ path: 'artifacts/visual-qa/121-weekly-report-desktop.png', fullPage: true })
})

test('child one-question flow is reachable, optional and touch friendly on phone', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page); await unlockParent(page, '/parent/assistant')
  await page.getByRole('checkbox', { name: /启用小队助手/ }).check()
  await page.getByRole('checkbox', { name: /孩子的一问一答/ }).check()
  await expect.poll(async () => Object.values((await persistedState(page)).modules.assistant.settingsByProfile).some((s) => s.enabled && s.childOneQuestion)).toBe(true)
  await page.goto('/bedtime/companion-question')
  await expect(page.getByText('不想回答可以跳过')).toBeVisible()
  await expect(page.locator('.companion-question section>div>button')).toHaveCount(3)
  await expectComfortable(page, [page.getByRole('button', { name: '这次先不回答' })])
  await expectImagesLoaded(page)
  await page.screenshot({ path: 'artifacts/visual-qa/122-companion-question-mobile.png', fullPage: true })
  await page.getByRole('button', { name: '这次先不回答' }).click()
  await expect(page).not.toHaveURL(/companion-question/)
})

test('terminal simulator renders its device art without profile switching or chat', async ({ page }) => {
  await page.setViewportSize({ width: 1180, height: 820 })
  await page.goto('/bedtime/terminal-simulator.html')
  await expect(page.getByRole('heading', { name: '口袋终端模拟器' })).toBeVisible()
  await expect(page.getByLabel('六位连接码')).toBeVisible()
  await expect(page.locator('select, textarea, [contenteditable="true"]')).toHaveCount(0)
  const background = await page.locator('.device').evaluate((element) => getComputedStyle(element).backgroundImage)
  expect(background).toContain('pocket-terminal.webp')
  await expectComfortable(page)
  await page.screenshot({ path: 'artifacts/visual-qa/123-terminal-simulator-desktop.png', fullPage: true })
})
