import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, addBook, persistedState, expectComfortable, expectImagesLoaded, completeBedtime } from './helpers.js'

test('V2 bedtime focus is optional, advances real tasks and preserves undo in overview', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page)
  const tasks = page.locator('.gs-task-grid>button')
  const count = await tasks.count()
  const first = await tasks.first().getAttribute('aria-label')
  await page.getByRole('button', { name: '专注一件', exact: true }).click()
  await expect(page.getByRole('region', { name: '专注一件睡前小事' })).toBeVisible()
  await expect(page.getByRole('heading', { name: first, exact: true })).toBeVisible()
  await expectComfortable(page, [page.getByRole('button', { name: '这件做好了' })])
  await page.screenshot({ path: 'artifacts/visual-qa/v2-bedtime-focus-phone.png', fullPage: true })
  await page.getByRole('button', { name: '这件做好了' }).click()
  await expect(page.getByRole('heading', { name: first, exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '回到总清单' }).click()
  await expect(tasks).toHaveCount(count)
  await expect(tasks.first()).toHaveAttribute('aria-pressed', 'true')
  await tasks.first().click()
  await expect(tasks.first()).toHaveAttribute('aria-pressed', 'false')
  await page.reload()
  await expect(tasks.first()).toHaveAttribute('aria-pressed', 'false')
})

test('V2 bookshelf searches four real books while keeping filters and reading journey intact', async ({ page }) => {
  await setupFamily(page)
  await unlockParent(page, '/parent/reading')
  for (const title of ['月亮小船', '机器人种子', '风里的树', '小兔回家']) await addBook(page, title)
  await page.goto('/bedtime/reading')
  await page.getByRole('searchbox', { name: '找一本书' }).fill('机器人')
  await expect(page.locator('.reading-books>button')).toHaveCount(1)
  await page.locator('.reading-books>button').click()
  await expect(page.locator('.v2-journey [aria-current=step]')).toContainText('陪着读')
  await page.getByRole('button', { name: '带我开始' }).click()
  await page.getByRole('button', { name: '读完啦' }).click()
  await expect(page.locator('.v2-journey [aria-current=step]')).toContainText('留句话')
  await page.screenshot({ path: 'artifacts/visual-qa/v2-reading-reflection.png', fullPage: true })
  await page.getByRole('button', { name: '以后再说', exact: true }).click()
  await expect.poll(async () => Object.values((await persistedState(page)).modules.reading.sessions).filter((s) => s.completedAt).length).toBe(1)
})

test('V2 family pulse switches children and quick actions open working parent pages', async ({ page }) => {
  await setupFamily(page)
  await unlockParent(page, '/parent/profile')
  await page.getByRole('button', { name: /新增孩子/ }).first().click()
  const dialog = page.getByRole('dialog', { name: '新增孩子' })
  await dialog.getByLabel('孩子昵称').fill('妹妹')
  await dialog.getByRole('button', { name: '建立孩子档案' }).click()
  await expect.poll(async () => (await persistedState(page)).profiles.length).toBe(2)
  await unlockParent(page)
  const family = page.getByRole('region', { name: '家庭近况' })
  await expect(family.locator('button')).toHaveCount(2)
  await family.getByRole('button', { name: /小语/ }).click()
  await expect(family.getByRole('button', { name: /小语/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByLabel('当前孩子')).toHaveValue(await family.getByRole('button', { name: /小语/ }).evaluate(() => JSON.parse(localStorage.getItem('growing-squad:main:v7')).profiles.find((p) => p.name === '小语').id))
  await page.screenshot({ path: 'artifacts/visual-qa/v2-parent-dashboard-desktop.png', fullPage: true })
  await page.getByRole('navigation', { name: '家长快捷操作' }).getByRole('button', { name: '记一条观察' }).click()
  await expect(page).toHaveURL(/\/parent\/support$/)
})

test('V2 backpack category switches show only real entries without generating rewards', async ({ page }) => {
  await setupFamily(page)
  await completeBedtime(page)
  await unlockParent(page, '/parent/reading')
  await addBook(page)
  await page.goto('/bedtime/reading')
  await page.locator('.reading-books>button').first().click()
  await page.getByRole('button', { name: '带我开始' }).click()
  await page.getByRole('button', { name: '读完啦' }).click()
  await page.getByRole('button', { name: '以后再说', exact: true }).click()
  await page.goto('/bedtime/me')
  const group = page.getByRole('group', { name: '背包里的记忆类型' })
  await group.getByRole('button', { name: '故事', exact: true }).click()
  await expect(page.locator('.calm-memory-list>button')).toHaveCount(1)
  await expect(page.locator('.calm-memory-list')).toContainText('刺猬')
  await group.getByRole('button', { name: '晚安', exact: true }).click()
  await expect(page.locator('.calm-memory-list')).toContainText('今晚的准备')
  await page.screenshot({ path: 'artifacts/visual-qa/v2-backpack-filter.png', fullPage: true })
})

for (const [name, width, height] of [['phone', 390, 844], ['tablet', 1194, 834], ['desktop', 1440, 1000]]) {
  test(`V2 illustrated screens and parent controls remain usable on ${name}`, async ({ page }) => {
    test.setTimeout(90000)
    await page.setViewportSize({ width, height })
    await setupFamily(page, { at: '2026-09-06T16:20:00+08:00' })
    for (const path of ['today', 'world', 'me', 'reading', 'movement', 'family-cottage', 'inventor']) {
      await page.goto(`/bedtime/${path}`)
      await expect(page.locator('h1').first()).toBeVisible()
      await expectComfortable(page)
      await expectImagesLoaded(page)
      await page.screenshot({ path: `artifacts/visual-qa/v2-${path}-${name}.png`, fullPage: true })
    }
    await unlockParent(page)
    await expect(page.getByRole('region', { name: '家庭近况' })).toBeVisible()
    await expectComfortable(page, [page.getByRole('navigation', { name: '家长快捷操作' }).getByRole('button').first()])
    await page.screenshot({ path: `artifacts/visual-qa/v2-parent-${name}.png`, fullPage: true })
  })
}

test('V2 reduced-motion preference stops decorative motion and keeps keyboard skip navigation', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await setupFamily(page)
  await page.goto('/bedtime/today')
  await expect(page.locator('.calm-card')).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.getAnimations().filter((a) => a.playState === 'running').length)).toBe(0)
  await page.keyboard.press('Tab')
  const skip = page.getByRole('link', { name: '跳到当前内容' })
  await expect(skip).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#child-content')).toBeFocused()
  await expectComfortable(page)
})
