/* global Buffer */
import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, persistedState, expectComfortable, expectImagesLoaded } from './helpers.js'

async function createProjectThroughTesting(page,seed='hair-robot') {
  await page.goto(`/bedtime/inventor/new?seed=${seed}`)
  await page.getByRole('button',{name:'把这个想法收进工坊'}).click()
  await expect(page.getByRole('heading',{name:'先把办法画下来'})).toBeVisible()
  await page.getByRole('button',{name:'草图准备好啦'}).click()
  await page.getByRole('button',{name:'第一版准备试一试'}).click()
  await expect(page.getByRole('heading',{name:'这次试出了什么？'})).toBeVisible()
}

test('invention keeps a first prototype, genuine attachment, testing, knowledge, iteration and archive',async({page}) => {
  test.setTimeout(120000)
  await page.setViewportSize({width:1366,height:900});await setupFamily(page)
  await page.goto('/bedtime/inventor')
  await page.getByRole('button',{name:'发现我的第一个想法'}).click()
  await page.getByRole('button',{name:'把这个想法收进工坊'}).click()
  await expect(page.getByRole('heading',{name:'先把办法画下来'})).toBeVisible()
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXs8AAAAASUVORK5CYII=','base64')
  await page.getByLabel('拍下第一版').setInputFiles({name:'草图.png',mimeType:'image/png',buffer:png})
  await expect(page.getByText('已保存在本机，联网后尝试同步到家庭设备。')).toBeVisible()
  await expect.poll(async() => Object.keys((await persistedState(page)).modules.inventor.artifacts).length).toBe(1)
  await page.reload();await expect(page.getByText('等网络恢复')).toBeVisible()
  await page.getByRole('button',{name:'草图准备好啦'}).click();await page.getByRole('button',{name:'第一版准备试一试'}).click()
  await page.getByRole('button',{name:'两边还会漏',exact:true}).click()
  await page.getByRole('button',{name:'把两边围起来',exact:true}).click()
  await page.getByRole('button',{name:'把测试发现收好'}).click();await expect(page.getByRole('heading',{name:'新线索已经收好'})).toBeVisible()
  await unlockParent(page,'/parent/inventor')
  await page.getByRole('button',{name:'放进孩子的下一步'}).first().click()
  await expect(page.getByText('这张小线索已经放进孩子的下一步。')).toBeVisible()
  await expect.poll(async() => (await persistedState(page)).modules.inventor.projects[0].knowledgeCardIds.length).toBe(1)
  await page.screenshot({path:'artifacts/visual-qa/inventor-parent-tablet.png',fullPage:true})
  await page.goto('/bedtime/inventor');await page.getByRole('button',{name:/继续往前走/}).click()
  await expect(page.getByRole('button',{name:'听眠眠讲一遍'})).toBeVisible()
  await page.getByRole('button',{name:'带着这个线索再改一版'}).click()
  await page.getByRole('button',{name:'第二版准备讲给家人听'}).click()
  await expect(page.getByRole('heading',{name:'我的发明故事'})).toBeVisible()
  await expect(page.locator('.inventor-story>div')).toHaveCount(4)
  await page.getByRole('button',{name:'把这次发明收进工坊'}).click()
  await expect.poll(async() => (await persistedState(page)).modules.inventor.projects[0].status).toBe('archived')
  const p=(await persistedState(page)).modules.inventor.projects[0]
  expect(p.versions).toHaveLength(2);expect(p.versions[0].testFindingTitle).toBe('两边还会漏')
  await page.getByRole('button',{name:/洗头机器人.*已收进工坊/}).click()
  await page.getByRole('button',{name:'我还想继续改'}).click();await expect(page.getByRole('heading',{name:'带着线索做第二版'})).toBeVisible()
})

test('phone focus-helper uses relevant findings and custom projects are real editable ideas',async({page}) => {
  await page.setViewportSize({width:390,height:844});await setupFamily(page);await createProjectThroughTesting(page,'focus-helper')
  await expect(page.getByRole('button',{name:'能看懂下一步了',exact:true})).toBeVisible()
  await expect(page.getByText('两边还会漏')).toHaveCount(0)
  await page.getByLabel('也可以用自己的话说（可选）').fill('一次只看一张卡更容易')
  await expectComfortable(page,[page.getByRole('button',{name:'把测试发现收好'})]);await expectImagesLoaded(page)
  await page.screenshot({path:'artifacts/visual-qa/inventor-focus-phone.png',fullPage:true})
  await page.getByRole('button',{name:'把测试发现收好'}).click()
  await expect.poll(async() => (await persistedState(page)).modules.inventor.projects[0].versions[0].testFindingTitle).toBe('一次只看一张卡更容易')
  await page.goto('/bedtime/inventor/new?seed=my-idea')
  await page.getByLabel('给想法起个名字').fill('玩具归位小助手')
  await page.getByLabel('我想解决的小麻烦').fill('妹妹的玩具总是找不到家')
  await page.getByRole('button',{name:'把这个想法收进工坊'}).click()
  await expect(page.getByText('玩具归位小助手',{exact:true})).toBeVisible()
  await expect.poll(async() => (await persistedState(page)).modules.inventor.projects.some((p) => p.problem==='妹妹的玩具总是找不到家')).toBe(true)
})
