import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, persistedState, expectComfortable, expectImagesLoaded } from './helpers.js'
test('child chooses an activity, returns from play and stores preference without rewards',async({page}) => {
  await setupFamily(page); await page.goto('/bedtime/world')
  await page.getByRole('button',{name:/能量广场/}).click(); await expect(page.getByRole('heading',{name:'今天想怎样动一动？'})).toBeVisible()
  await page.locator('.movement-picks>button').first().click(); await page.getByRole('button',{name:'我准备好啦'}).click()
  await expect(page.getByRole('heading',{name:'去玩吧，屏幕在这里等你'})).toBeVisible()
  await page.getByRole('button',{name:'我回来啦'}).click(); await page.getByRole('button',{name:/还想玩/}).click()
  await expect.poll(async() => Object.values((await persistedState(page)).modules.movement.sessions).some((s) => s.feedback==='again')).toBe(true)
  await page.reload(); const state=await persistedState(page)
  expect(Object.values(state.growth.world).flatMap((w) => w.energyFlowers || [])).toHaveLength(1)
  expect(state.rewards.starLedger).toHaveLength(0)
})
test('phone has reachable movement controls and a way back to the world',async({page}) => {
  await page.setViewportSize({width:390,height:844}); await setupFamily(page); await page.goto('/bedtime/movement')
  await expectComfortable(page,['换两个','和家长一起','今天先不做'].map((name) => page.getByRole('button',{name,exact:true})))
  await page.getByRole('button',{name:'换两个'}).click(); await expect(page.locator('.movement-picks>button')).toHaveCount(2)
  await page.locator('.movement-picks>button').first().click(); await page.getByRole('button',{name:'我准备好啦'}).click()
  await expectComfortable(page,[page.getByRole('button',{name:'我回来啦'})]); await expectImagesLoaded(page)
  await page.screenshot({path:'artifacts/visual-qa/movement-play-phone.png',fullPage:true})
  await page.getByRole('button',{name:/返回小队世界/}).click(); await expect(page).toHaveURL(/\/world$/)
})
test('parent sees honest participation and an explicit indoor-only mode',async({page}) => {
  await setupFamily(page); await unlockParent(page,'/parent/movement')
  await expect(page.getByRole('heading',{name:'运动小队'})).toBeVisible()
  await expect(page.getByText('参与过的运动')).toBeVisible()
  await expect(page.getByText(/仅凭点击开始，无法判断是否主动/)).toBeVisible()
  await expect(page.locator('.movement-library__grid article')).toHaveCount(20)
  await page.getByRole('checkbox').check()
  await expect.poll(async() => Object.values((await persistedState(page)).modules.movement.preferencesByProfile).some((p) => p.rainMode)).toBe(true)
  await page.goto('/bedtime/movement'); await expect(page.locator('.movement-picks')).not.toContainText('户外')
})
