import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, addBook, persistedState, expectComfortable, expectImagesLoaded } from './helpers.js'

test('reading preserves real mode, help, words and attribution without rewards', async ({page}) => {
  await page.setViewportSize({width:1366,height:900}); await setupFamily(page); await unlockParent(page,'/parent/reading')
  await addBook(page); await addBook(page,'小星星找到了回家的路','追星星')
  const before=(await persistedState(page)).rewards.starLedger.length
  await page.goto('/bedtime/reading')
  await page.getByRole('button',{name:/刺猬的勇敢小灯笼的封面/}).click()
  await expect(page.locator('.reading-mode-grid>button')).toHaveCount(3)
  await page.getByRole('button',{name:/一起读/}).click(); await page.getByRole('button',{name:'带我开始'}).click()
  await expect(page.getByRole('heading',{name:'故事在你手里'})).toBeVisible()
  await page.getByRole('button',{name:'我需要帮助'}).click()
  await expect(page.getByText('已记录你需要帮助，请叫家长来陪一下。')).toBeVisible()
  await page.getByRole('button',{name:'读完啦'}).click()
  await page.getByRole('button',{name:/刚刚好/}).click(); await page.getByRole('button',{name:'说给它听'}).click()
  await page.getByLabel('留下一句话（可选，家长可以帮记）').fill('我会先帮小刺猬找灯笼')
  await page.getByLabel('这段话来自谁').selectOption('child')
  await page.getByRole('button',{name:'收进故事树屋'}).click()
  await expect(page.getByText('家中绘本 · 读过')).toBeVisible(); await page.reload()
  await expect(page.getByText('家中绘本 · 读过')).toBeVisible()
  await expect.poll(async() => Object.values((await persistedState(page)).modules.reading.sessions).some((s) => s.reflection?.note==='我会先帮小刺猬找灯笼' && s.reflection.noteSource==='child')).toBe(true)
  expect((await persistedState(page)).rewards.starLedger).toHaveLength(before)
  await page.getByRole('button',{name:/小星星找到了回家的路的封面/}).click(); await page.getByRole('button',{name:'带我开始'}).click(); await page.getByRole('button',{name:'先放回书架'}).click()
  await expect(page.getByText('继续上次的故事')).toBeVisible(); await page.reload(); await expect(page.getByText('继续上次的故事')).toBeVisible()
  await unlockParent(page,'/parent/report')
  await expect(page.getByText('我会先帮小刺猬找灯笼')).toBeVisible(); await expect(page.getByText('孩子原话',{exact:true})).toBeVisible()
  await expectImagesLoaded(page); await expectComfortable(page)
  await page.screenshot({path:'artifacts/visual-qa/reading-real-note-tablet.png',fullPage:true})
})
test('phone reading has three main choices, expandable modes and genuinely optional reflection', async ({page}) => {
  await page.setViewportSize({width:390,height:844}); await setupFamily(page); await unlockParent(page,'/parent/reading'); await addBook(page)
  await page.goto('/bedtime/reading'); await page.getByRole('button',{name:/刺猬的勇敢小灯笼的封面/}).click()
  await expect(page.locator('.reading-mode-grid>button')).toHaveCount(3)
  await page.getByRole('button',{name:'看看其他线下读法'}).click(); await expect(page.locator('.reading-mode-grid>button')).toHaveCount(8)
  await page.getByRole('button',{name:'收起更多方式'}).click(); await expect(page.locator('.reading-mode-grid>button')).toHaveCount(3)
  await expectComfortable(page,[page.getByRole('button',{name:'带我开始'})]); await page.getByRole('button',{name:'带我开始'}).click()
  await page.getByRole('button',{name:'读完啦'}).click()
  await expect(page.getByRole('button',{name:'以后再说'})).toBeEnabled()
  await expectComfortable(page,[page.getByRole('button',{name:'以后再说'})]); await expectImagesLoaded(page)
  await page.screenshot({path:'artifacts/visual-qa/reading-reflection-phone.png',fullPage:true})
  await page.getByRole('button',{name:'以后再说'}).click(); await expect(page).toHaveURL(/story-treehouse/)
  await expect.poll(async() => Object.values((await persistedState(page)).modules.reading.sessions).some((s) => s.status==='done' && s.reflection?.mode==='skip' && !s.difficulty)).toBe(true)
})
