import { expect, test } from '@playwright/test'

async function setupFamily(page) {
  await page.goto('/bedtime/')
  await page.evaluate(() => window.localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: /和孩子一起开始/ }).click()
  await page.getByLabel('孩子昵称').fill('小语')
  await page.getByLabel('家长区 PIN').fill('2468')
  await page.getByRole('button', { name: /保存并看看今晚/ }).click()
}

async function unlockParent(page) {
  await page.goto('/bedtime/parent/reading')
  for (const digit of ['2', '4', '6', '8']) await page.getByRole('button', { name: digit, exact: true }).click()
}

async function addBook(page, title = '刺猬的勇敢小灯笼', cover = '灯笼刺猬') {
  await page.getByRole('button', { name: /添加家里的书/ }).click()
  await page.getByLabel('书名').fill(title)
  await page.getByLabel('作者（可不填）').fill('家中绘本')
  await page.getByRole('button', { name: cover, exact: true }).click()
  await page.getByRole('button', { name: '放上书架', exact: true }).click()
}

test('child reading loop persists mode, help, difficulty and optional reflection without rewards', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 900 })
  await setupFamily(page)
  await unlockParent(page)
  await addBook(page)
  for (const [title, cover] of [['小星星找到了回家的路', '追星星'], ['叶子船的奇妙旅行', '叶子船'], ['小兔子的四季菜园', '四季菜园'], ['会说话的大树爷爷', '会说话的树'], ['云朵上的悄悄话', '云朵悄悄话']]) await addBook(page, title, cover)
  await page.goto('/bedtime/reading')
  await expect(page.getByRole('heading', { name: '故事树屋' })).toBeVisible()
  await expect(page.getByText(/星光|奖励|排名|速度|计时|分钟/)).toHaveCount(0)
  await page.getByRole('button', { name: /刺猬的勇敢小灯笼的封面/ }).click()
  await expect(page.getByRole('heading', { name: '这次想怎么读？' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/96-reading-mode-ipad.png', fullPage: true })
  await page.getByRole('button', { name: /一起读/ }).click()
  await page.getByRole('button', { name: '带我开始' }).click()
  await expect(page.getByRole('heading', { name: '故事在你手里' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/97-reading-active-ipad.png', fullPage: true })
  await page.getByRole('button', { name: '我需要帮助' }).click()
  await expect(page.getByText('已经告诉家长，等一等就会来陪你。')).toBeVisible()
  await page.getByRole('button', { name: '读完啦' }).click()
  await page.getByRole('button', { name: /刚刚好/ }).click()
  await page.getByRole('button', { name: '今天先不讲' }).click()
  await page.getByRole('button', { name: '收进故事树屋' }).click()
  await expect(page.getByText('家中绘本 · 读过')).toBeVisible()
  await page.reload()
  await expect(page.getByText('家中绘本 · 读过')).toBeVisible()
  await page.getByRole('button', { name: /小星星找到了回家的路的封面/ }).click()
  await page.getByRole('button', { name: '带我开始' }).click()
  await page.getByRole('button', { name: '先放回书架' }).click()
  await expect(page.getByText('继续上次的故事')).toBeVisible()
  await expect(page.getByRole('link', { name: '今天' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/93-reading-shelf-ipad.png', fullPage: true })
  await page.reload()
  await expect(page.getByText('继续上次的故事')).toBeVisible()

  await unlockParent(page)
  await expect(page.getByText('刺猬的勇敢小灯笼').first()).toBeVisible()
  await expect(page.getByText('一起读 · 刚刚好', { exact: true })).toBeVisible()
  await expect(page.getByText(/请求过帮助/)).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/98-reading-parent-desktop.png', fullPage: true })
})

test('phone keeps the entire reading decision and reflection in one viewport', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page)
  await unlockParent(page)
  await addBook(page)
  await page.goto('/bedtime/reading')
  const book = page.getByRole('button', { name: /刺猬的勇敢小灯笼的封面/ })
  await expect(book).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(844)
  await book.click()
  for (const label of ['听家长读', '一起读', '角色读', '自己读一点', '带我开始', '今天先不读']) await expect(page.getByRole('button', { name: new RegExp(label) })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(844)
  await page.getByRole('button', { name: '带我开始' }).click()
  await page.getByRole('button', { name: '读完啦' }).click()
  for (const label of ['很轻松', '刚刚好', '有点难', '说给它听', '画一张图', '演给它看', '今天先不讲', '收进故事树屋']) await expect(page.getByRole('button', { name: new RegExp(label) })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeLessThanOrEqual(844)
  await page.screenshot({ path: 'artifacts/visual-qa/94-reading-reflection-mobile.png', fullPage: true })
})
