import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, persistedState } from './helpers.js'

test('child and parent journeys are reversible, with all 16 tasks visible on the target tablet', async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page)
  await page.goto('/bedtime/today')
  const childNav = page.getByRole('navigation', { name: '儿童主导航' })
  for (const label of ['今天', '小队世界', '成长背包']) await expect(childNav.getByRole('link', { name: label })).toBeVisible()
  await expect(page.locator('.gs-next-card')).toBeVisible()
  await expect(page.locator('.gs-continue-card')).toBeVisible()
  await page.getByRole('link', { name: '小队世界' }).click()
  await expect(page.getByRole('button', { name: /月光花园/ })).toBeVisible()
  await page.getByRole('link', { name: '成长背包' }).click()
  await expect(page.getByRole('heading', { name: /收集的每一份成长/ })).toBeVisible()
  await unlockParent(page, '/parent/routine')
  await page.getByRole('button', { name: '周末', exact: true }).click()
  const initialEnabled = await page.locator('.gs-routine-list > article:not(.is-disabled)').count()
  for (let index = initialEnabled; index < 16; index += 1) {
    await page.getByRole('button', { name: /添加任务/ }).click()
    await page.getByRole('button', { name: '完成编辑' }).click()
  }
  await expect(page.getByRole('button', { name: '已到 16 项上限' })).toBeDisabled()
  await page.getByRole('button', { name: '保存流程' }).click()
  await expect.poll(async () => (await persistedState(page)).modules.bedtime.routines.some((r) => r.dayType==='weekend' && r.steps.filter((s) => s.enabled).length===16)).toBe(true)
  await page.getByRole('button', { name: '孩子模式' }).click()
  await page.setViewportSize({ width: 1194, height: 834 })
  await expect(page.locator('.gs-task-grid button')).toHaveCount(16)
  await page.screenshot({ path: 'artifacts/visual-qa/tonight-sixteen-tablet.png', fullPage: true })
  const taskButtons = page.locator('.gs-task-grid button')
  const visible = await taskButtons.evaluateAll((buttons) => buttons.filter((button) => { const r=button.getBoundingClientRect(); return r.top>=0 && r.bottom<=innerHeight }).length)
  expect(visible).toBe(16)
  for (let index = 0; index < 16; index += 1) { await taskButtons.nth(index).click(); await expect(taskButtons.nth(index)).toHaveAttribute('aria-pressed','true') }
  await expect(page.getByRole('button', { name: /完成今晚任务/ })).toBeEnabled()
  await taskButtons.nth(0).click()
  await expect(page.getByRole('button', { name: /再完成 1 项/ })).toBeDisabled()
  await expect(page.locator('.star-balance')).toContainText('0')
  await unlockParent(page)
  await page.setViewportSize({ width: 390, height: 844 })
  const parentNav = page.getByRole('navigation', { name: '家长导航' })
  for (const label of ['今天', '成长', '计划', '奖励', '设置']) await expect(parentNav.getByRole('link', { name: label })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390)
})
