import { expect, test } from '@playwright/test'

async function setupFamily(page) {
  await page.goto('/bedtime/')
  await page.evaluate(() => window.localStorage.clear())
  await page.reload()
  await page.getByRole('button', { name: /和孩子一起开始/ }).click()
  await page.getByLabel('孩子昵称').fill('小语')
  await page.getByLabel('家长区 PIN').fill('2468')
  await page.getByRole('button', { name: /保存并看看今晚/ }).click()
}

async function unlockParent(page, next = '/bedtime/parent/responsibility') {
  await page.goto(next)
  for (const digit of ['2', '4', '6', '8']) await page.getByRole('button', { name: digit, exact: true }).click()
}

test('one child completes a real family role and creates belonging without rewards', async ({ page }) => {
  await page.setViewportSize({ width: 1366, height: 900 })
  await setupFamily(page)
  await page.goto('/bedtime/family-cottage')
  await expect(page.getByRole('heading', { name: '家庭小屋' })).toBeVisible()
  await expect(page.getByText(/积分|排行榜|连续打卡|完成次数/)).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/visual-qa/100-family-cottage-ipad.png', fullPage: true })

  await page.getByRole('button', { name: /晚饭前准备餐桌/ }).first().click()
  await expect(page.getByText('你来负责')).toBeVisible()
  await expect(page.locator('.responsibility-role__people>div')).toHaveCount(2)
  await page.screenshot({ path: 'artifacts/visual-qa/101-family-role-ipad.png', fullPage: true })
  await page.getByRole('button', { name: '大家准备好啦' }).click()
  await expect(page.getByRole('button', { name: '我做好啦' })).toBeVisible()
  await expect(page.getByText(/计时|星光|金币|排名/)).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/visual-qa/102-family-active-ipad.png', fullPage: true })
  await page.getByRole('button', { name: '我做好啦' }).click()
  await expect(page.getByRole('heading', { name: '我们一起准备好了' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/103-family-complete-ipad.png', fullPage: true })
  await page.getByRole('button', { name: '收进家庭小屋' }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '家庭小屋' })).toBeVisible()
})

test('two children receive different roles and create only one shared moment', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 800 })
  await setupFamily(page)
  await unlockParent(page, '/bedtime/parent/profile')
  await page.getByRole('button', { name: '新增孩子' }).first().click()
  const dialog = page.getByRole('dialog', { name: '新增孩子' })
  await dialog.getByLabel('孩子昵称').fill('小雨')
  await dialog.getByRole('button', { name: '建立孩子档案' }).click()
  await page.goto('/bedtime/family-cottage')
  await page.getByRole('button', { name: /晚饭前准备餐桌/ }).first().click()
  await expect(page.locator('.responsibility-role__people>div')).toHaveCount(3)
  const allRoles = await page.locator('.responsibility-role__people>div strong').allTextContents()
  const childRoles = allRoles.slice(0, -1)
  expect(childRoles).toHaveLength(2)
  expect(new Set(childRoles.map((item) => item.split('·')[1]?.trim())).size).toBe(2)
  await page.getByRole('button', { name: '大家准备好啦' }).click()
  await page.getByRole('button', { name: '我做好啦' }).click()
  await expect(page.getByRole('heading', { name: '我的小角色做好了' })).toBeVisible()

  await unlockParent(page, '/bedtime/parent/profile')
  await page.getByRole('button', { name: /小语/ }).first().click()
  await page.goto('/bedtime/family-cottage')
  await page.getByRole('button', { name: /继续我的小角色/ }).click()
  await page.getByRole('button', { name: '我做好啦' }).click()
  await expect(page.getByRole('heading', { name: '我们一起准备好了' })).toBeVisible()
  await unlockParent(page)
  await expect(page.getByText('家庭共同记录')).toBeVisible()
  await expect(page.locator('.responsibility-moments>article')).toHaveCount(1)
  await expect(page.locator('.responsibility-moments>article small')).toContainText('小语')
  await expect(page.getByText(/排行榜|谁做得多|完成次数/)).toHaveCount(0)
})

test('phone and parent planner keep every primary action visible and usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page)
  await page.goto('/bedtime/family-cottage')
  let metrics = await page.evaluate(() => ({ document: document.documentElement.scrollHeight, viewport: innerHeight, width: document.documentElement.scrollWidth, viewportWidth: innerWidth }))
  expect(metrics.document).toBeLessThanOrEqual(metrics.viewport)
  expect(metrics.width).toBeLessThanOrEqual(metrics.viewportWidth)
  await page.getByRole('button', { name: /晚饭前准备餐桌/ }).first().click()
  await page.getByRole('button', { name: '大家准备好啦' }).click()
  for (const name of ['我做好啦', '我需要帮助', '先回家庭小屋']) await expect(page.getByRole('button', { name })).toBeVisible()
  await page.getByRole('button', { name: '我需要帮助' }).click()
  metrics = await page.evaluate(() => ({ document: document.documentElement.scrollHeight, viewport: innerHeight, width: document.documentElement.scrollWidth, viewportWidth: innerWidth }))
  expect(metrics.document).toBeLessThanOrEqual(metrics.viewport)
  expect(metrics.width).toBeLessThanOrEqual(metrics.viewportWidth)
  await page.screenshot({ path: 'artifacts/visual-qa/104-family-active-mobile.png', fullPage: true })

  await page.setViewportSize({ width: 1440, height: 960 })
  await unlockParent(page)
  await expect(page.getByRole('heading', { name: '家庭责任' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '小语需要帮助' })).toBeVisible()
  await page.screenshot({ path: 'artifacts/visual-qa/105-family-parent-desktop.png', fullPage: true })
  await page.getByRole('button', { name: '已经回应孩子' }).click()
  await expect(page.getByRole('heading', { name: '暂时没有求助' })).toBeVisible()
  await page.getByRole('button', { name: /安静模式/ }).click()
  await expect(page.getByText('当前：安静模式')).toBeVisible()
  await page.getByRole('button', { name: /轮换一次/ }).click()
  await page.getByRole('button', { name: /安排家庭活动/ }).click()
  await page.getByLabel('选择活动').selectOption('plant-care')
  await page.getByRole('button', { name: '保存家庭活动' }).click()
  await expect(page.getByRole('heading', { name: '家庭责任' })).toBeVisible()
  await expect(page.getByText(/排行榜|完成次数|谁做得多/)).toHaveCount(0)
  await page.screenshot({ path: 'artifacts/visual-qa/106-family-parent-configured.png', fullPage: true })
})
