import { expect, test } from '@playwright/test'

async function setup(page) {
  await page.clock.setFixedTime(new Date('2026-09-06T07:20:00+08:00'))
  await page.goto('/bedtime/')
  await page.getByRole('button',{name:/我先替孩子设置/}).click()
  await page.getByLabel('孩子昵称').fill('小语')
  await page.getByLabel('家长区 PIN').fill('2468')
  await page.getByRole('button',{name:/保存并看看今晚/}).click()
  await expect(page).toHaveURL(/\/tonight$/)
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('growing-squad:main:v7') || '{}').setupComplete)).toBe(true)
}
test('setup is durable before navigation; morning and afternoon have complete independent loops',async({page}) => {
  await setup(page)
  await page.goto('/bedtime/today')
  await expect(page.locator('.calm-card')).toHaveAttribute('data-state','ready')
  await page.locator('.calm-choices>button').first().click()
  await expect(page.getByRole('button',{name:/我做完了/})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:/我做完了/}).click()
  await expect(page.locator('.calm-card')).toHaveAttribute('data-state','completed')
  await page.clock.setFixedTime(new Date('2026-09-06T16:20:00+08:00'))
  await page.reload()
  await expect(page.locator('.calm-choices>button')).toHaveCount(2)
  await page.getByRole('button',{name:'稍后再做'}).click()
  await expect(page.locator('.calm-card')).toHaveAttribute('data-state','paused')
  await page.locator('.calm-choices>button').first().click()
  await expect(page.getByRole('button',{name:/我做完了/})).toBeVisible()
  await page.getByRole('button',{name:/我做完了/}).click()
  await expect(page.locator('.calm-card')).toHaveAttribute('data-state','completed')
})
test('empty world and backpack do not invent personal achievements',async({page}) => {
  await setup(page)
  await page.goto('/bedtime/me')
  await expect(page.getByRole('heading',{name:'第一份记忆，还在路上'})).toBeVisible()
  await expect(page.getByText('我自己准备好了书包')).toHaveCount(0)
  await page.goto('/bedtime/world')
  await expect(page.getByText('0 / 5 个地方留下了记忆')).toBeVisible()
  await expect(page.getByText('奇妙的夜空')).toHaveCount(0)
})
test('phone choices and keyboard dialog stay usable; escape restores focus',async({page}) => {
  await page.setViewportSize({width:390,height:844})
  await setup(page)
  await page.clock.setFixedTime(new Date('2026-09-06T16:20:00+08:00'))
  await page.goto('/bedtime/today')
  await expect(page.locator('.calm-choices>button')).toHaveCount(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  for(const button of await page.locator('.calm-choices>button,.calm-support>button').all()) expect((await button.boundingBox()).height).toBeGreaterThanOrEqual(44)
  await page.getByRole('button',{name:'需要帮助',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button',{name:'需要帮助',exact:true})).toBeFocused()
  await page.screenshot({path:'artifacts/visual-qa/comfort-today-phone.png',fullPage:true})
})
