import { expect, test } from '@playwright/test'
import { setupFamily, unlockParent, addBook, expectImagesLoaded } from './helpers.js'

async function capture(page, name) {
  await expect(page.locator('h1').first()).toBeVisible()
  await expectImagesLoaded(page)
  await expect.poll(() => page.locator('#child-content, #parent-content').evaluateAll((nodes) => nodes.every((node) => getComputedStyle(node).transform === 'none'))).toBe(true)
  await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }))
  await page.screenshot({ path: `artifacts/visual-qa/v2-final-${name}.png` })
}

test('mobile overview keeps visible task controls and final views are captured at rest', async ({ page }) => {
  test.setTimeout(90000)
  await page.setViewportSize({ width: 390, height: 844 })
  await setupFamily(page, { at: '2026-09-06T16:20:00+08:00' })
  await page.goto('/bedtime/today')
  await expect(page.locator('.calm-card')).toBeVisible()
  await capture(page, 'today-phone')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await capture(page, 'today-desktop')
  await unlockParent(page)
  await capture(page, 'parent-desktop')
  await page.setViewportSize({ width: 390, height: 844 })
  await capture(page, 'parent-phone')
  await page.goto('/bedtime/world')
  await expect(page.locator('.v2-world-landscape')).toBeVisible()
  await capture(page, 'world-phone')
  await page.goto('/bedtime/tonight')
  await expect(page.locator('.gs-task-grid>button').first()).toBeVisible()
  await capture(page, 'bedtime-overview-phone')
  await expect(page.locator('.gs-task-grid>button').first()).toBeInViewport()
  await expect(page.getByRole('button', { name: '调整今晚任务' })).toBeInViewport()
  await expect(page.locator('.gs-tonight-scene')).toBeVisible()
  await unlockParent(page, '/parent/reading')
  await addBook(page)
  await page.goto('/bedtime/reading')
  await expect(page.getByRole('heading', { name: '故事树屋' })).toBeVisible()
  await capture(page, 'reading-shelf-phone')
  await page.locator('.reading-books>button').first().click()
  await capture(page, 'reading-mode-phone')
  await page.getByRole('button', { name: '带我开始' }).click()
  await page.getByRole('button', { name: '读完啦' }).click()
  await capture(page, 'reading-reflection-phone')
  await page.getByRole('button', { name: '以后再说', exact: true }).click()
})
