import { useRef, useState } from 'react'
import { Modal } from '../Shared.jsx'
import { useGentleMotion } from '../v2/useGentleMotion.js'
import { EggArt, PetActor, PetProp } from './PetArt.jsx'
import { PET_SPECIES, PET_ITEMS, getSpecies, getPetItem } from '../../modules/pets/petCatalog.js'
import { levelProgress, badgeBalance, BADGES_PER_LEVEL, signatureFor, LEVEL_COSTS, evolveStage } from '../../modules/pets/petEconomy.js'
import { petBalance, growthRequestStatus, petAllowanceLeft } from '../../modules/pets/petModel.js'
import { uid } from '../../domain/model.js'
import './pet-economy.css'

export function EggMeadow({species,name,onSpecies,onName,onAdopt,busy,message}) {
  const [hints,setHints]=useState(true)
  const chosen=getSpecies(species), ref=useGentleMotion(species)
  return <section className="pet-egg-meadow" aria-labelledby="pet-adopt-title">
    <header className="egg-meadow-heading"><div><span className="pet-eyebrow">一个小世界 · 等你来发现</span><h1 id="pet-adopt-title">选一颗喜欢的蛋</h1><p>先看看，再决定。每一颗蛋都能免费认识。</p></div><label className="egg-hint-toggle"><input type="checkbox" checked={hints} onChange={e=>setHints(e.target.checked)}/>看看小提示</label></header>
    <div className="egg-meadow-layout">
      <div className="egg-meadow-field"><div className="pet-species-grid egg-sea" role="group" aria-label="选择星光蛋">{PET_SPECIES.map((option,i)=><button type="button" key={option.id} className="egg-sea-choice" aria-pressed={species===option.id} aria-label={`${option.eggName}，${option.name}，免费预览`} onClick={()=>onSpecies(option)} style={{'--egg-delay':`${i*.03}s`}}><span className="egg-grass"/><EggArt species={option.id}/><strong>{option.eggName}</strong><span className="egg-hint">{hints?option.name:'点开认识我'}</span>{species===option.id?<span className="egg-selected" aria-hidden="true">✓</span>:null}</button>)}</div><p className="egg-field-note">没有稀有等级，不花星光选蛋，也不用重抽。</p></div>
      <form className="egg-preview-card" onSubmit={event=>{event.preventDefault();onAdopt()}}>
        <span className="pet-eyebrow">这颗蛋里，原来是…</span><div ref={ref} className="egg-preview-friend"><PetActor species={species} pose="wave" size="baby" motion="wave"/></div><h2>{chosen.name}</h2><p>{chosen.copy}</p><label className="pet-field">给小伙伴取个名字<input required maxLength={12} value={name} onChange={e=>onName(e.target.value)} placeholder="例如：糯糯"/></label><button className="pet-button" type="submit" disabled={busy||!name.trim()}>把这颗蛋带回家</button><small>选定后陪它破壳。先养一只主伙伴，好好认识彼此。</small><p role="status">{message}</p>
      </form>
    </div>
  </section>
}
export function PetWallets({stars,badges,onShop,onGrow}) {
  return <div className="pet-wallet-pair"><button type="button" className="pet-wallet pet-wallet--stars" onClick={onGrow} aria-label={`星光培养，余额 ${stars} 星光`}><PetProp kind="star"/><span><small>星光 · 培养</small><strong>{stars}</strong></span></button><button type="button" className="pet-wallet pet-wallet--badges" onClick={onShop} aria-label={`徽章小铺，余额 ${badges} 枚徽章`}><PetProp kind="badge"/><span><small>徽章 · 兑换</small><strong>{badges}</strong></span></button></div>
}
export function CultivationPanel({state,pet,profileId,now,onSend,onProgress,busy,standalone=false}) {
  const [amount,setAmount]=useState(1),[confirm,setConfirm]=useState(false)
  const progress=levelProgress(pet), balance=petBalance(state,profileId)
  const status=growthRequestStatus(state,profileId,amount,now)
  const latest=Object.values(state.modules.pets.requests).filter(r=>r.profileId===profileId&&r.kind==='growth'&&r.status==='approved'&&r.levels?.length).sort((a,b)=>b.approvedAt-a.approvedAt)[0]
  const pending=status.request || Object.values(state.modules.pets.requests).find(r=>r.profileId===profileId&&r.kind==='growth'&&r.status==='pending')
  const signature=signatureFor(pet)
  async function invest() {
    const next=await onSend('PET_REQUEST_GROWTH',{amount,requestId:uid('cultivation')})
    if(next){setConfirm(false);const after=next.modules.pets.byProfile[profileId];if(after.economy.invested>pet.economy.invested)onProgress({pet:after,from:progress.level,to:levelProgress(after).level,amount})}
  }
  return <section className={`cultivation-card ${standalone?'cultivation-card--full':''}`} aria-label="星光培养">
    <div className="cultivation-top"><div className="cultivation-level"><span>Lv.</span><strong>{progress.level}</strong></div><div className="cultivation-progress"><div><strong>{progress.maxed?'已经达到 20 级啦':`再投入 ${progress.remaining} 颗，就到 ${progress.level+1} 级`}</strong><small>{progress.maxed?'已经学会的本领和回忆一直保留':`${progress.progress} / ${progress.cost}`}</small></div><progress aria-label="当前等级成长进度" max={progress.cost||1} value={progress.cost?progress.progress:1}/><span>每升一级 +{BADGES_PER_LEVEL} 枚徽章 · 普通吃饭不花星光</span></div></div>
    {!progress.maxed&&pet.hatchedAt?<div className="cultivation-controls"><div className="cultivation-amounts" role="group" aria-label="选择培养星光数量">{[1,3,5].map(n=><button type="button" key={n} aria-pressed={amount===n} className="pet-button pet-button--soft" onClick={()=>setAmount(n)}>{n} 颗</button>)}<label>自选<input type="number" aria-label="本次培养星光数量" min="1" max={Math.min(50,progress.capacity)} step="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label></div><button type="button" className="pet-button cultivate-primary" disabled={busy||!status.allowed} onClick={()=>setConfirm(true)}>喂一点星光</button></div>:null}
    {!pet.hatchedAt?<p className="pet-small-note">先迎接它出生。孵化免费，星光留着长大后再用。</p>:!status.allowed&&!progress.maxed?<p className="pet-small-note">{status.label}</p>:null}
    {pending?<div className="cultivation-pending"><span>等家长回应：{pending.amount} 颗星光，尚未扣除</span><button type="button" className="pet-text-button" disabled={busy} onClick={()=>onSend('PET_CANCEL_ITEM',{requestId:pending.id})}>取消这次申请</button></div>:null}
    {standalone?<>{pet.economy?.migrated?<p className="pet-small-note">旧伙伴、物品和已经长大的模样都保留。从这次星光培养开始记录新等级，不补发历史徽章。</p>:null}<div className="cultivation-roadmap"><article><span>2 级</span><strong>开始转圈</strong><p>开放练习，慢慢变熟练</p></article><article><span>3 级</span><strong>{signature.name}</strong><p>新模样 + 自己的专属本领</p></article><article><span>6 级</span><strong>长成大伙伴</strong><p>成长装饰升级，已学本领保留</p></article></div><p className="pet-small-note">升级开放练习，不需要再花星光练习。已拥有的本领道具也可以提前开放对应练习。每次点击不会自动赚积分。</p><details className="pet-growth-rules"><summary>看看升级规则与培养记录</summary><p>1 颗星光 = 1 点成长进度。确认后永久投入；申请被拒绝或取消不扣星。满 20 级后不再收取星光。</p><div className="level-cost-list">{LEVEL_COSTS.map((cost,i)=><span key={i}>{i+1} → {i+2} 级：{cost} 颗</span>)}</div><ol>{Object.values(state.modules.pets.requests).filter(r=>r.profileId===profileId&&r.kind==='growth').sort((a,b)=>b.requestedAt-a.requestedAt).slice(0,12).map(r=><li key={r.id}>{r.amount} 颗星光 · {({pending:'等家长回应',approved:`已培养${r.levels?.length?`，获得 ${r.levels.length*15} 枚徽章`:''}`,cancelled:'已取消，未扣星',declined:'这次先不培养'})[r.status]}</li>)}</ol></details></>:null}
    {latest?<button className="pet-text-button" type="button" onClick={()=>onProgress({pet,from:latest.levels[0]-1,to:latest.levels.at(-1),amount:latest.amount,replay:true})}>重看最近一次升级</button>:null}
    {confirm?<Modal title="确认这次星光培养" onClose={()=>setConfirm(false)} className="pet-modal"><div className="growth-confirm"><PetActor species={pet.species} size="baby"/><h2>给{pet.name} {amount} 颗星光</h2><p>当前 {balance} 颗，{status.auto?'培养后':'批准后'}还剩 <strong>{balance-amount} 颗</strong>。</p><p>{status.auto?`这在今天的自主额度内，还可自主使用 ${petAllowanceLeft(state,profileId,now)} 颗。`:'先请家长同意。发送申请不会扣星，批准时才投入。'}</p><p className="pet-small-note">星光与现实愿望共用余额。投入的成长永久保留，不能换回星光；普通吃饭、喝水和睡觉一直免费。</p><button type="button" className="pet-button" disabled={busy||!status.allowed} onClick={invest}>{status.label}</button><button type="button" className="pet-text-button" onClick={()=>setConfirm(false)}>再想一想</button></div></Modal>:null}
  </section>
}
export function GrowthCelebration({result,onClose}) {
  const gained=Math.max(0,result.to-result.from),ref=useGentleMotion(result)
  const stage=evolveStage(result.pet),tier=stage==='companion'?'adult':stage
  return <Modal title={gained?'新的成长时刻':'星光已经收到'} onClose={onClose} className="pet-modal growth-celebration"><div ref={ref}><span className="pet-eyebrow">{result.replay?'回看这段回忆 · 不会再次发奖励':'这是我们一起养大的小伙伴'}</span><div className="growth-celebration-scene"><PetActor species={result.pet.species} size={tier} motion={gained?'celebrate':'growth'}/><span className="growth-star-trail" aria-hidden="true"><PetProp kind="star"/><PetProp kind="star"/><PetProp kind="star"/></span></div><h2>{gained?`${result.pet.name}升到 ${result.to} 级啦`:`收到 ${result.amount} 颗星光`}</h2>{gained?<div className="badge-reward"><PetProp kind="badge"/><strong>+{gained*15}</strong><span>枚徽章</span></div>:<p>成长进度已经收好，下次可以接着培养。</p>}<button type="button" className="pet-button" onClick={onClose}>抱抱小伙伴</button></div></Modal>
}
const CATEGORIES=[['all','全部'],['house','房子'],['dress','裙子'],['decor','家具'],['toy','玩具'],['skill','本领道具'],['story','故事'],['room','房间主题']]
export function BadgeShop({pet,onItem,onGoal,onCancelGoal,busy}) {
  const [category,setCategory]=useState('all'), balance=badgeBalance(pet),goal=getPetItem(pet.life?.goalItemId)
  return <section className="pet-panel badge-shop"><header className="badge-shop-heading"><div><span className="pet-eyebrow">升级的小礼物 · 自己挑喜欢的</span><h2>徽章小铺</h2><p>裙子 1 枚 · 小房子 2 枚 · 永久拥有</p></div><span className="badge-shop-balance"><PetProp kind="badge"/><strong>{balance}</strong><small>枚可用</small></span></header>{goal?<div className="pet-goal"><PetProp kind={goal.art}/><div><strong>我想要：{goal.name}</strong><p>{balance>=goal.badgePrice?'已经够啦，先看看喜欢不喜欢。':`还差 ${goal.badgePrice-balance} 枚徽章，不会过期。`}</p></div><button type="button" className="pet-text-button" disabled={busy} onClick={onCancelGoal}>先不设目标</button></div>:null}<div className="pet-filters" role="group" aria-label="小铺分类">{CATEGORIES.map(([id,label])=><button type="button" key={id} aria-pressed={category===id} onClick={()=>setCategory(id)}>{label}</button>)}</div><div className="badge-item-grid">{PET_ITEMS.filter(item=>category==='all'||item.category===category).sort((a,b)=>({dress:0,house:1,decor:2,toy:3,skill:4,story:5,room:6}[a.category]??7)-({dress:0,house:1,decor:2,toy:3,skill:4,story:5,room:6}[b.category]??7)).map(item=><article className={`badge-item ${pet.inventory[item.id]?'is-owned':''}`} key={item.id}><button type="button" className="badge-item-art" aria-label={`预览${item.name}`} onClick={()=>onItem(item)}><PetProp kind={item.art}/></button><h3>{item.name}</h3><span className="badge-item-price"><PetProp kind="badge"/>{item.badgePrice} 枚{pet.inventory[item.id]?' · 已拥有':''}</span><button type="button" className="pet-button pet-button--soft" onClick={()=>onItem(item)}>{pet.inventory[item.id]?'看看怎么用':'先看看'}</button>{!pet.inventory[item.id]&&balance<item.badgePrice?<button type="button" className="pet-text-button" disabled={busy} onClick={()=>onGoal(item.id)}>记下这个小愿望</button>:null}</article>)}</div><div className="badge-shop-note"><PetProp kind="bowl"/><p>升级才会得到徽章，物品不再花星光购买。基础照顾一直免费，没有充值、限时抢购或抽奖。</p></div><details className="pet-growth-rules"><summary>徽章从哪里来、花到哪里了</summary><ol>{[...(pet.economy?.badgeLedger||[])].reverse().slice(0,30).map(entry=><li key={entry.id}>{entry.delta>0?'+':''}{entry.delta} 枚 · {entry.reason==='level'?`升到 ${entry.level} 级`:entry.reason==='refund'?'撤销物品兑换':'兑换物品'}</li>)}</ol></details></section>
}
export function BadgeItemDialog({item,pet,busy,onClose,onBuy,onUse,onGoal}) {
  const [preview,setPreview]=useState(false), pending=useRef(false)
  const owned=Boolean(pet.inventory[item.id]), enough=badgeBalance(pet)>=item.badgePrice
  async function buy(){if(pending.current)return;pending.current=true;try{await onBuy(item)}finally{pending.current=false}}
  return <Modal title={item.name} onClose={onClose} className="pet-modal badge-item-dialog"><div className="badge-detail-preview">{item.category==='dress'?<PetActor species={pet.species} size="young" dress={preview?item.art:''}/>:<><PetProp kind={item.art}/>{['house','room'].includes(item.category)?<span className="badge-detail-resident"><PetActor species={pet.species} size="baby"/></span>:null}</>}</div><h2>{item.name}</h2><p>{item.copy}</p>{item.category==='dress'?<button type="button" className="pet-button pet-button--soft" aria-pressed={preview} onClick={()=>setPreview(v=>!v)}>{preview?'脱下看看':'试穿一下，不扣徽章'}</button>:null}<div className="badge-item-price"><PetProp kind="badge"/><strong>{item.badgePrice} 枚徽章</strong></div><p>{owned?'已经永久拥有，不会再扣款。':`现在有 ${badgeBalance(pet)} 枚${enough?`，兑换后剩 ${badgeBalance(pet)-item.badgePrice} 枚`:'，可以先记下这个小愿望'}。`}</p>{owned?<button type="button" className="pet-button" onClick={()=>onUse(item)}>去使用</button>:<button type="button" className="pet-button" disabled={busy||!enough} onClick={buy}>确认兑换 · {item.badgePrice} 枚徽章</button>}{!owned&&!enough?<button type="button" className="pet-text-button" onClick={()=>onGoal(item.id)}>记下这个小愿望</button>:null}<small className="pet-small-note">不花星光。兑换后 30 秒内，家长可以撤销物品兑换；已投入宠物的成长不倒退。</small></Modal>
}

export function ParentEconomyInbox({pet,requests,stars,busy,now,onAction}) {
  const pending=requests.filter(r=>r.status==='pending')
  const title=r=>r.kind==='growth'?`培养${pet?.name||'小伙伴'} ${r.amount} 颗星光`:getPetItem(r.itemId)?.name||'历史物件'
  const unit=r=>r.currency==='badge'?'枚徽章':'颗星光'
  return <section className="pet-panel parent-economy-inbox"><header><h2>{pending.length?`${pending.length} 份培养申请等你回应`:'暂时没有待回应的培养申请'}</h2><p>培养申请不预扣；批准时检查星光余额。徽章兑换不再花星光。</p></header>{pending.map(r=><article className="pet-approval" key={r.id}><PetProp kind={r.kind==='growth'?'star':getPetItem(r.itemId)?.art}/><div><h3>{title(r)}</h3><p>{r.cost} {unit(r)} · 当前可用 {stars} 颗星光</p>{r.kind==='growth'?<small>批准后星光将永久投入宠物，成长与升级徽章一起保存。</small>:null}</div><div className="pet-approval-actions"><button type="button" className="pet-button" disabled={busy||stars<r.cost} onClick={()=>onAction('PET_APPROVE_ITEM',{requestId:r.id},'已批准，培养与徽章记录已经保存。')}>同意这次培养</button><button type="button" className="pet-button pet-button--soft" disabled={busy} onClick={()=>onAction('PET_DECLINE_ITEM',{requestId:r.id},'这次先不培养，没有扣星光。')}>先不培养</button></div></article>)}<h3>最近的培养与兑换</h3>{requests.slice(0,18).map(r=><div className="pet-receipt" key={r.id}><span><strong>{title(r)}</strong><small>{r.migrationReason?'旧星光物品申请已取消，未扣款，请到徽章小铺重新选择':r.status==='approved'?`已${r.kind==='growth'?'培养':'兑换'} · −${r.cost} ${unit(r)}${r.levels?.length?` · +${r.levels.length*15} 枚徽章`:''}`:r.status==='refunded'?`已撤销 · 返还 ${r.cost} ${unit(r)}`:r.status==='pending'?'等待回应，未扣款':r.status==='declined'?'这次先不，未扣款':'已取消，未扣款'}</small></span>{r.status==='approved'&&r.kind!=='growth'&&now>=r.approvedAt&&now-r.approvedAt<=30000?<button type="button" className="pet-text-button" disabled={busy} onClick={()=>onAction('PET_REFUND_ITEM',{requestId:r.id},`已返还${unit(r)}，物件已收回。`)}>撤销物品兑换</button>:null}</div>)}{!requests.length?<div className="pet-empty"><PetProp kind="badge"/><p>还没有培养或兑换记录。可以先免费照顾和玩耍。</p></div>:null}<p className="pet-small-note">培养不能事后换回星光，未批准申请可取消。物品兑换后 30 秒内可撤销，返还原来的币种，宠物不降级。</p></section>
}
